# 46. 제너레이터와 async/await
## 46.1 제너레이터란?
코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수 ES6 도입
1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.
2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.
3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.
## 46.2 제너레이터 함수의 정의
function* 키워드로 선언하며, 하나 이상의 yield 표현식을 포함

화살표 함수로 정의할 수 없으며, new 연산자와 함께 생성자 함수로 호출할 수 없음
## 46.3 제너레이터 객체
제너레이터 함수가 반환한 제너레이터 객체는 Symbol.iterator 메서드를 상속받는 이터러블이면서

value, done 프로퍼티를 갖는 이터레이터 리절트 객체를 반환하는 next 메서드를 소유하는 이터레이터
```
function* genFunc() {
  yield 1;
  yield 2;
  yield 3;
}

// 제너레이터 함수를 호출하면 제너레이터 객체를 반환
const generator = genFunc();

console.log(Symbol.iterator in generator);  // true
console.log('next' in generator);  // true
```
- next 메서드를 호출하면 제너레이터 함수의 yield 표현식까지 코드 블록을 실행하고 yield된 값을 value 프로퍼티 값으로, false를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환
- return 메서들를 호출하면 인수로 전달받은 값을 value 프로퍼티 값으로, true를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환
- throw 메서드를 호출하면 인수로 전달받은 에러를 발생시키고 undefined를 value 프로퍼티 값으로, true를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환
```
function* genFunc() {
  try {
    yield 1;
    yield 2;
    yield 3;
  } catch (e) {
    console.log(e);
  }
}

const generator = genFunc();

console.log(generator.next());  // {value: 1, done: false}
console.log(generator.return('End!'));  // {value: "End!", done: true}
console.log(generator.throw('Error!'));  // {value: undefined, done: true}
```
## 46.4 제너레이터의 일시 중지와 재개
일반함수는 호출 이후 제어권을 함수가 독점하지만 제너레이터는 함수 호출자에게 제어권을 양도하여 필요한 시점에 함수 실행을 재개할 수 있음
```
function* genFunc() {
  // 처음 next 메서드를 호출하면 첫 번째 yield 표현식까지 실행되고 일시 중단
  // yield된 값 1은 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당
  // x 변수에는 아직 값이 할당되지 않았으며, next 메서드가 두 번째 호출될 때 결정됨
  // 두 번째 next 메서드에 전달한 인수가 x에 할당됨
  const x = yield 1;

  const y = yield (x + 10);

  // 제너레이터 함수의 반환값은 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당됨
  // 일반적으로 제너레이터의 반환값은 의미가 없기 때문에 종료의 의미로만 사용
  return x + y;
}

const generator = genFunc();

let res = generator.next();
console.log(res);  // {value: 1, done: false}

res = generator.next(10);
console.log(res);  // {value: 20, done: false}

res = generator.next(20);
console.log(res);  // {value: 30, done: true}
```
yield 키워드는 제너레이터 함수의 실행을 일시 중지시키거나 yield 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환
## 46.5 제너레이터의 활용
### 46.5.1 이터러블의 구현
이터레이션 프로토콜을 준수해 이터러블을 생성하는 방식보다 간단하게 이터러블 구현 가능
```
// 무한 이터러블을 생성하는 함수
cons infiniteFibonacci = (function() {
  let [pre, cur] = [0, 1];

  return {
    [Symbol.iterator]() { return this; },
    next() {
      [pre, cur] = [cur, pre + cur];
      return {value: cur};
    }
  };
}());

for (const num of infiniteFibonacci) {
  if (num > 10000) break;
  console.log(num);  // 1 2 3 5 8 ... 2584 4181 6765
}
```
```
const infinitFibonacci = (function* () {
  let [pre, cur] = [0, 1];

  while (true) {
    [pre, cur] = [cur, pre + cur];
    yield cur;
  }
}());

for (const num of infiniteFibonacci) {
  if (num > 10000) break;
  console.log(num);  // 1 2 3 5 8 ... 2584 4181 6765
}
```
### 46.5.2 비동기 처리
next 메서드와 yield 표현식을 통해 함수 호출자와 함수의 상태를 주고받을 수 있어 프로미스를 사용한 비동기 처리를 동기 처리처럼 구현할 수 있음
```
const fetch = require('node-fetch');

const async = generatorFunc => {
  const generator = generatorFunc();
  const onResolved = arg => {
    const result = generator.next(arg);

    return result.done
      ? result.value
      : result.value.then(res => onResolved(res));
  };
  return onResolved;
};

(async(function* fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';

  const response = yield fetch(url);
  const todo = yield response.json();
  console.log(todo);
  // {userId: 1, id: 1, title: `delectus aut autem', completed: false}
})());
```
## 46.6 async/ await
프로미스의 then/catch/finally 후속 처리 메서드에 콜백 함수를 전달해서 비동기 처리 결과를 후속 처리할 필요 없이 마치 동기처럼 프로미스를 사용 가능
```
const fetch = require('node-fetch');

function fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';

  fetch(url)
    .then(response => {
      if (!response.ok) {
        throw new Error(`에러 발생`);
      }
      return response.json();
    })
    .then(todo => {
      console.log(todo);
    })
    .catch(error => {
      console.error('Error:', error);
    })
}

fetchTodo();
```
```
const fetch = require('node-fetch');

async function fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';

  const response = await fetch(url);
  const todo = await response.json();
  console.log(todo);
}

fetchTodo();
```
### 46.6.1 async 함수
await 키워드는 반드시 async 함수 내부에서 사용

async 키워드를 사용해 정의하며 언제나 프로미스를 반환값을 resolve하는 프로미스를 반환
### 46.6.2 await 키워드
프로미스가 settled 상태가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 처리 결과를 반환

await 키워드는 반드시 프로미스 앞에서 사용

서로 연관없이 개별적으로 수행되는 비동기 처리의 경우 비동기 처리가 완료될 때까지 대기해서 순차적으로 처리할 필요가 없기 때문에 Promise.all 사용

```
async function foo() {
  const a = await new Promise(resolve => setTimeout(() => resolve(1), 3000));
  const b = await new Promise(resolve => setTimeout(() => resolve(2), 2000));
  const c = await new Promise(resolve => setTimeout(() => resolve(3), 1000));

  console.log([a, b, c]);  // [1, 2,  3]
}

foo();  // 약 6초 소요
```
```
async function foo() {
  const res = await Promise.all([
    new Promise(resolve => setTimeout(() => resolve(1), 3000)),
    new Promise(resolve => setTimeout(() => resolve(2), 2000)),
    new Promise(resolve => setTimeout(() => resolve(3), 1000)),
  ]);

  console.log(res);  // [1, 2, 3]
}

foo();  // 약 3초 소요
```
단, 비동기 처리의 순서가 보장되어야 할 경우 모든 프로미스에 await 키워드를 써서 순차적으로 처리
```
async function bar(n) {
  const a = await new Promise(resolve => setTimeout(() => resolve(n), 3000));
  const b = await new Promise(resolve => setTimeout(() => resolve(a + 1, 2000));
  const c = await new Promise(resolve => setTimeout(() => resolve(b + 1, 1000));

  console.log([a, b, c]);  // [1, 2,  3]
}

foo();  // 약 6초 소요
```
### 46.6.3 에러 처리
비동기 처리를 위한 콜백 패턴의 단점은 호출자 방향으로 전파되기 때문에(실행 중인 실행 컨텍스트) 비동기 함수의 콜백 함수의 에러를 캐치할 수 없음

async/ await의 에러 처리는 프로미스를 반환하는 비동기 함수는 명시적으로 호출하여 호출자가 명확하기 때문에 try ... catch 문 사용 가능

catch 문은 HTTP 통신에서 발생한 네트워크 에러 뿐만 아니라 try 코드 블록 내의 모든 문에서 발생한 일반적인 에러까지 모두 캐치 가능
```
const fetch = require('node-fetch');

const foo = async () => {
  try {
    const wrongUrl = 'https://wrong.url';

    const response = await fetch(wrongUrl);
    const data = await response.json();
    console.log(data);
  } catch (err) {
    console.error(err);  // TypeError: Failed to fetch
  }
};

foo();
```

# 47. 에러 처리
## 47.1 에러 처리의 필요성
에러가 발생하지 않는 코드를 작성하는 것은 불가능하며, 발생한 에러에 대해 대처하지 않고 방치하면 프로그램은 강제 종료됨

try...catch 문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지않고 계속해서 코드를 실행시킬 수 있음 

querySelector나 Array.find 메서드처럼 예외적인 상황이 발생하면 반환하는 값을 if 문이나 단축 평가, 옵셔널 체이닝 연산자를 통해 확인해서 처리할 수 있음
## 47.2 try...catch...finally 문
## 47.3 Error 객체
Error 생성자 함수는 에러 객체를 생성하며, 이 객체는 message 프로퍼티와 stack 프로퍼티를 가짐

자바스크립트는 Error 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 Error.prototype을 상속받는 Error 생성자 함수를 제공
|생성자 함수|인스턴스|
|:--:|:--:|
|Error|일반적인 에러 객체|
|SyntaxError|자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체|
|ReferenceError|참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체|
|TypeError|피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체|
|RangeError|숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체|
|URIError|encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체|
|EvalError|eval 함수에서 발생하는 에러 객체|

## 47.4 throw 문
Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니며, 에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야함
## 47.5 에러의 전파
에러는 호출자 방향으로, 콜 스택의 아래 방향인 실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향으로 전파됨

호출자 방향으로 전파되어 에러를 캐치할 수 있음

중첩 실행 컨텍스트 => 함수 실행 컨텍스트 => 전역 실행 컨텍스트

# 48. 모듈
## 48.1 모듈의 일반적 의미
## 48.2 자바스크립트와 모듈
## 48.3 ES6 모듈(ESM)
### 48.3.1 모듈 스코프
### 48.3.2 export 키워드
### 48.3.3 import 키워드

# 49. Babel과 Webpack을 이용한 ES6+/ES.NEXT 개발 환경 구축
## 49.1 Babel
### 49.1.1 Babel 설치
### 49.1.2 Babel 프리셋 설치와 babel.config.json 설정 파일 작성
### 49.1.3 트랜스파일링
### 49.1.4 Babel 플러그인 설치
### 49.1.5 브라우저에서 모듈 로딩 테스트
## 49.2 Webpack
### 49.2.1 Webpack 설치
### 49.2.2 babel-loader 설치
### 49.2.3 webpack.config.js 설정 파일 작성
